#!/bin/sh
# _                                   
#| |__  ___ _ ____      ___ __ ___  
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_|   ~by nichtgestalt

#source $HOME/.local/share/scripts

# SXHKD - Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Dunst
pkill dunst && dunst || dunst &

if [ $(xrandr | grep -wc 'connected') -eq 2 ]
then
	pkill polybar
	xrandr --output LVDS-1 --primary --mode 1600x900 --pos 1920x180 --rotate normal --output HDMI-3 --mode 1920x1080 --pos 0x0 --rotate normal
	Display1=$(xrandr | grep -w 'connected' | awk 'FNR==1{printf$1')
	Display2=$(xrandr | grep -w 'connected' | awk 'FNR==2{printf$1')
	bspc monitor $Display2 -d "1" "2" "3" "4" "5"
	bspc monitor $Display1 -d "6" "7" "8" "9" 
	polybar bspwm &
	polybar external &
	notify-send "multi monitor" &
else
	Display0=$(xrander | grep -w 'connected' | awk '{printf$1}')
	bspc monitor $Display0 -d "1" "2" "3" "4" "5" "6" "7"
fi


# Activate Polybar
pkill polybar && polybar bspwm || polybar bspwm & 
# Gaps and Borders
bspc config border_width           0
bspc config normal_border_color   "#5c6370"
bspc config focused_border_color  "#3073db"
bspc config presel_feedback_color "#3f444a"

bspc config window_gap             0
bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true


# Window Rules
bspc rule -a Nitrogen              state=floating
bspc rule -a Ristretto             state=floating
bspc rule -a Gpick                 state=floating
bspc rule -a Toolkit               state=floating
bspc rule -a Parole                state=floating


# Autostart
nitrogen  --restore &
xsetroot  -cursor_name left_ptr &
picom --backend glx --vsync &
unclutter -idle 3 -root &
#polybar-msg cmd hide; bspc config top_padding +0
#bspc desktop -f '^4' &
sleep 0.05
xset r rate 250 30 &
setxkbmap de neo &
#!/bin/sh
